"""The texts both apps show -- the single source for them.

The Android and iOS apps used to keep their own copies of these (``strings.xml`` / ``translations.py``),
and the copies drifted apart (a different Dutch wording of the same boat-mode status line on each
platform). The iOS app now reads TEXTS directly; the Android app's ``strings.xml`` is generated from
it (``python -m nmea2log.export_android_strings <res dir>``), so a wording is changed here once.

Placeholders are named (``{time}``, ``{count}``) and substituted with ``str.format``; the Android
export numbers them in the order they first appear in the English text (``%1$s``, ``%2$d``) and
takes each one's type (``s``/``d``) from the string it replaces. Only texts the two apps share live
here; a text that exists on one platform only stays in that app.
"""

from __future__ import annotations

from typing import Dict

TEXTS: Dict[str, Dict[str, str]] = {
    "section_w2k2_boat": {
        "en": "W2K-2 & boat",
        "nl": "W2K-2 & boot",
        "fr": "W2K-2 et bateau",
        "de": "W2K-2 & Boot",
    },
    "label_w2k2_user": {
        "en": "W2K-2 username",
        "nl": "W2K-2 gebruikersnaam",
        "fr": "Nom d'utilisateur W2K-2",
        "de": "W2K-2-Benutzername",
    },
    "label_w2k2_password": {
        "en": "W2K-2 password",
        "nl": "W2K-2 wachtwoord",
        "fr": "Mot de passe W2K-2",
        "de": "W2K-2-Passwort",
    },
    "label_boat_name": {
        "en": "Boat name",
        "nl": "Bootnaam",
        "fr": "Nom du bateau",
        "de": "Bootsname",
    },
    "label_mmsi": {
        "en": "MMSI",
        "nl": "MMSI",
        "fr": "MMSI",
        "de": "MMSI",
    },
    "label_call_sign": {
        "en": "Call sign",
        "nl": "Roepnaam",
        "fr": "Indicatif d'appel",
        "de": "Rufzeichen",
    },
    "checkbox_auto_sync_on_launch": {
        "en": "Download automatically on launch",
        "nl": "Automatisch downloaden bij starten",
        "fr": "Télécharger automatiquement au démarrage",
        "de": "Beim Start automatisch herunterladen",
    },
    "section_trips": {
        "en": "Trips",
        "nl": "Reizen",
        "fr": "Trajets",
        "de": "Fahrten",
    },
    "label_min_stop_minutes": {
        "en": "Minimum stop duration to count as a port visit (minutes)",
        "nl": "Minimale stop-tijd om als havenbezoek te tellen (minuten)",
        "fr": "Durée d'arrêt minimale pour compter comme escale (minutes)",
        "de": "Mindeststandzeit, um als Hafenbesuch zu zählen (Minuten)",
    },
    "checkbox_auto_publish_after_build": {
        "en": "Publish automatically after assembling",
        "nl": "Automatisch publiceren na samenstellen",
        "fr": "Publier automatiquement après l'assemblage",
        "de": "Nach dem Zusammenstellen automatisch veröffentlichen",
    },
    "section_publish": {
        "en": "Publish",
        "nl": "Publiceren",
        "fr": "Publier",
        "de": "Veröffentlichen",
    },
    "radio_publish_none": {
        "en": "Don't publish (local only)",
        "nl": "Niet publiceren (alleen lokaal)",
        "fr": "Ne pas publier (local uniquement)",
        "de": "Nicht veröffentlichen (nur lokal)",
    },
    "radio_publish_wordpress": {
        "en": "Publish via WordPress",
        "nl": "Publiceren via WordPress",
        "fr": "Publier via WordPress",
        "de": "Über WordPress veröffentlichen",
    },
    "radio_publish_sftp": {
        "en": "Publish via SFTP",
        "nl": "Publiceren via SFTP",
        "fr": "Publier via SFTP",
        "de": "Über SFTP veröffentlichen",
    },
    "label_rest_upload_url": {
        "en": "WordPress site address",
        "nl": "WordPress-siteadres",
        "fr": "Adresse du site WordPress",
        "de": "WordPress-Website-Adresse",
    },
    "label_rest_upload_user": {
        "en": "WordPress username",
        "nl": "WordPress gebruikersnaam",
        "fr": "Nom d'utilisateur WordPress",
        "de": "WordPress-Benutzername",
    },
    "label_rest_upload_password": {
        "en": "WordPress application password",
        "nl": "WordPress application password",
        "fr": "Mot de passe d'application WordPress",
        "de": "WordPress-Anwendungspasswort",
    },
    "label_sftp_host": {
        "en": "SFTP host",
        "nl": "SFTP host",
        "fr": "Hôte SFTP",
        "de": "SFTP-Host",
    },
    "label_sftp_port": {
        "en": "SFTP port",
        "nl": "SFTP poort",
        "fr": "Port SFTP",
        "de": "SFTP-Port",
    },
    "label_sftp_user": {
        "en": "SFTP username",
        "nl": "SFTP gebruikersnaam",
        "fr": "Nom d'utilisateur SFTP",
        "de": "SFTP-Benutzername",
    },
    "label_sftp_password": {
        "en": "SFTP password",
        "nl": "SFTP wachtwoord",
        "fr": "Mot de passe SFTP",
        "de": "SFTP-Passwort",
    },
    "label_sftp_remote_path": {
        "en": "SFTP path on the server",
        "nl": "SFTP pad op de server",
        "fr": "Chemin SFTP sur le serveur",
        "de": "SFTP-Pfad auf dem Server",
    },
    "label_sftp_host_key_fingerprint": {
        "en": "SFTP host key fingerprint (optional; empty = trust automatically on first connection)",
        "nl": "SFTP host-key fingerprint (optioneel; leeg = automatisch vertrouwen bij eerste verbinding)",
        "fr": "Empreinte de clé hôte SFTP (facultatif ; vide = faire confiance automatiquement à la première connexion)",
        "de": "SFTP-Hostschlüssel-Fingerabdruck (optional; leer = bei erster Verbindung automatisch vertrauen)",
    },
    "section_boat_mode": {
        "en": "Boat mode",
        "nl": "Boot-modus",
        "fr": "Mode bateau",
        "de": "Boot-Modus",
    },
    "label_boat_interval": {
        "en": "A round (download + assemble) every",
        "nl": "Een ronde (downloaden + samenstellen) elke",
        "fr": "Une ronde (télécharger + assembler) toutes les",
        "de": "Eine Runde (Herunterladen + Zusammenstellen) alle",
    },
    "boat_interval_30": {
        "en": "30 minutes",
        "nl": "30 minuten",
        "fr": "30 minutes",
        "de": "30 Minuten",
    },
    "boat_interval_60": {
        "en": "1 hour",
        "nl": "1 uur",
        "fr": "1 heure",
        "de": "1 Stunde",
    },
    "boat_interval_120": {
        "en": "2 hours",
        "nl": "2 uur",
        "fr": "2 heures",
        "de": "2 Stunden",
    },
    "boat_interval_180": {
        "en": "3 hours",
        "nl": "3 uur",
        "fr": "3 heures",
        "de": "3 Stunden",
    },
    "checkbox_boat_publish_every_round": {
        "en": "Publish after every round",
        "nl": "Elke ronde publiceren",
        "fr": "Publier après chaque ronde",
        "de": "Nach jeder Runde veröffentlichen",
    },
    "checkbox_boat_final_harbour": {
        "en": "Final round once the boat is in harbour",
        "nl": "Laatste ronde zodra de boot in de haven ligt",
        "fr": "Dernière ronde dès que le bateau est au port",
        "de": "Letzte Runde, sobald das Boot im Hafen liegt",
    },
    "label_boat_harbour_stationary_minutes": {
        "en": "Harbour: stationary for (minutes)",
        "nl": "Haven: stil gedurende (minuten)",
        "fr": "Port : à l'arrêt depuis (minutes)",
        "de": "Hafen: stillstehend seit (Minuten)",
    },
    "label_boat_harbour_engine_off_minutes": {
        "en": "Harbour: engine off for (minutes)",
        "nl": "Haven: motor uit gedurende (minuten)",
        "fr": "Port : moteur coupé depuis (minutes)",
        "de": "Hafen: Motor aus seit (Minuten)",
    },
    "checkbox_boat_final_left": {
        "en": "Final round when I have left the boat",
        "nl": "Laatste ronde als ik van boord ben",
        "fr": "Dernière ronde quand j'ai quitté le bateau",
        "de": "Letzte Runde, wenn ich das Boot verlassen habe",
    },
    "label_boat_left_minutes": {
        "en": "Left the boat: W2K-2 unreachable for (minutes)",
        "nl": "Van boord: W2K-2 niet bereikbaar gedurende (minuten)",
        "fr": "Quitté le bateau : W2K-2 injoignable depuis (minutes)",
        "de": "Boot verlassen: W2K-2 nicht erreichbar seit (Minuten)",
    },
    "checkbox_boat_stop_after_final": {
        "en": "Turn off after final round",
        "nl": "Uitzetten na laatste ronde",
        "fr": "Désactiver après la dernière ronde",
        "de": "Nach letzter Runde ausschalten",
    },
    "checkbox_boat_auto_start": {
        "en": "Turn on automatically on launch",
        "nl": "Automatisch inschakelen bij starten",
        "fr": "Activer automatiquement au démarrage",
        "de": "Beim Start automatisch einschalten",
    },
    "boat_status_searching": {
        "en": "Boat mode: looking for the W2K-2...",
        "nl": "Boot-modus: zoeken naar de W2K-2...",
        "fr": "Mode bateau : recherche du W2K-2...",
        "de": "Boot-Modus: Suche nach dem W2K-2...",
    },
    "boat_status_round_started": {
        "en": "Boat mode: round started (download and assemble)...",
        "nl": "Boot-modus: ronde gestart (downloaden en samenstellen)...",
        "fr": "Mode bateau : ronde démarrée (téléchargement et assemblage)...",
        "de": "Boot-Modus: Runde gestartet (Herunterladen und Zusammenstellen)...",
    },
    "boat_status_round_done": {
        "en": "Boat mode: round done, next round at {time}.",
        "nl": "Boot-modus: ronde klaar, volgende ronde om {time}.",
        "fr": "Mode bateau : ronde terminée, prochaine ronde à {time}.",
        "de": "Boot-Modus: Runde abgeschlossen, nächste Runde um {time}.",
    },
    "boat_status_round_failed": {
        "en": "Boat mode: round failed, trying again.",
        "nl": "Boot-modus: ronde mislukt, opnieuw proberen.",
        "fr": "Mode bateau : ronde échouée, nouvel essai.",
        "de": "Boot-Modus: Runde fehlgeschlagen, neuer Versuch.",
    },
    "boat_status_w2k2_not_found_retry": {
        "en": "Boat mode: W2K-2 not reachable, trying again at {time}.",
        "nl": "Boot-modus: W2K-2 niet bereikbaar, opnieuw om {time}.",
        "fr": "Mode bateau : W2K-2 injoignable, nouvel essai à {time}.",
        "de": "Boot-Modus: W2K-2 nicht erreichbar, neuer Versuch um {time}.",
    },
    "boat_status_harbour_final": {
        "en": "Boat mode: the boat is in harbour, final round.",
        "nl": "Boot-modus: de boot ligt in de haven, laatste ronde.",
        "fr": "Mode bateau : le bateau est au port, dernière ronde.",
        "de": "Boot-Modus: Das Boot liegt im Hafen, letzte Runde.",
    },
    "boat_status_left_boat": {
        "en": "Boat mode: left the boat (W2K-2 gone), final round.",
        "nl": "Boot-modus: van boord (W2K-2 weg), laatste ronde.",
        "fr": "Mode bateau : bateau quitté (W2K-2 absent), dernière ronde.",
        "de": "Boot-Modus: Boot verlassen (W2K-2 weg), letzte Runde.",
    },
    "boat_status_left_boat_nothing": {
        "en": "Boat mode: left the boat, nothing new to publish.",
        "nl": "Boot-modus: van boord, niets nieuws om te publiceren.",
        "fr": "Mode bateau : bateau quitté, rien de nouveau à publier.",
        "de": "Boot-Modus: Boot verlassen, nichts Neues zu veröffentlichen.",
    },
    "boat_status_waiting_in_port": {
        "en": "Boat mode: waiting in port, next check at {time}.",
        "nl": "Boot-modus: wacht in de haven, volgende controle om {time}.",
        "fr": "Mode bateau : attente au port, prochain contrôle à {time}.",
        "de": "Boot-Modus: wartet im Hafen, nächste Prüfung um {time}.",
    },
    "boat_status_publish_started": {
        "en": "Boat mode: publishing...",
        "nl": "Boot-modus: publiceren...",
        "fr": "Mode bateau : publication...",
        "de": "Boot-Modus: Veröffentlichen...",
    },
    "boat_status_publish_ok": {
        "en": "Boat mode: published.",
        "nl": "Boot-modus: gepubliceerd.",
        "fr": "Mode bateau : publié.",
        "de": "Boot-Modus: veröffentlicht.",
    },
    "boat_status_publish_failed": {
        "en": "Boat mode: publishing failed, trying again at {time}.",
        "nl": "Boot-modus: publiceren mislukt, opnieuw om {time}.",
        "fr": "Mode bateau : échec de la publication, nouvel essai à {time}.",
        "de": "Boot-Modus: Veröffentlichen fehlgeschlagen, neuer Versuch um {time}.",
    },
    "boat_status_stopped": {
        "en": "Boat mode stopped.",
        "nl": "Boot-modus gestopt.",
        "fr": "Mode bateau arrêté.",
        "de": "Boot-Modus beendet.",
    },
    "tooltip_boat_mode_on": {
        "en": "Turn off boat mode",
        "nl": "Boot-modus uitschakelen",
        "fr": "Désactiver le mode bateau",
        "de": "Boot-Modus ausschalten",
    },
    "section_appearance": {
        "en": "Appearance",
        "nl": "Weergave",
        "fr": "Apparence",
        "de": "Darstellung",
    },
    "radio_theme_light": {
        "en": "Light",
        "nl": "Licht",
        "fr": "Clair",
        "de": "Hell",
    },
    "radio_theme_dark": {
        "en": "Dark",
        "nl": "Donker",
        "fr": "Sombre",
        "de": "Dunkel",
    },
    "radio_theme_system": {
        "en": "Follow device",
        "nl": "Apparaat volgen",
        "fr": "Suivre l'appareil",
        "de": "Gerät folgen",
    },
    "section_cache": {
        "en": "Clear cache",
        "nl": "Cache legen",
        "fr": "Vider le cache",
        "de": "Cache leeren",
    },
    "button_clear": {
        "en": "Clear",
        "nl": "Legen",
        "fr": "Vider",
        "de": "Leeren",
    },
    "button_cache_data": {
        "en": "Decoded/assembled trip data",
        "nl": "Gedecodeerde/samengestelde reisdata",
        "fr": "Données de trajets décodées/assemblées",
        "de": "Dekodierte/zusammengestellte Fahrtdaten",
    },
    "button_cache_places": {
        "en": "Place names, weather & wave data",
        "nl": "Plaatsnamen, weer- en golfgegevens",
        "fr": "Noms de lieux, météo et houle",
        "de": "Ortsnamen, Wetter- und Wellendaten",
    },
    "button_save": {
        "en": "Save",
        "nl": "Opslaan",
        "fr": "Enregistrer",
        "de": "Speichern",
    },
    "button_cancel": {
        "en": "Cancel",
        "nl": "Annuleren",
        "fr": "Annuler",
        "de": "Abbrechen",
    },
    "dialog_clear_data_cache_message": {
        "en": "Clear all decoded and assembled trip data? The next download will decode and process every .ebl file again from scratch (takes longer, but nothing is lost -- the .ebl files themselves stay in place).",
        "nl": "Alle gedecodeerde en samengestelde reisdata wissen? Bij het eerstvolgende downloaden worden dan alle .ebl-bestanden opnieuw gedecodeerd en verwerkt vanaf het begin (duurt langer, maar er gaat niets verloren -- de .ebl-bestanden zelf blijven staan).",
        "fr": "Effacer toutes les données de trajets décodées et assemblées ? Le prochain téléchargement décodera et traitera à nouveau chaque fichier .ebl depuis le début (plus long, mais rien n'est perdu -- les fichiers .ebl eux-mêmes restent en place).",
        "de": "Alle dekodierten und zusammengestellten Fahrtdaten löschen? Der nächste Download dekodiert und verarbeitet dann alle .ebl-Dateien erneut von Anfang an (dauert länger, aber es geht nichts verloren -- die .ebl-Dateien selbst bleiben erhalten).",
    },
    "dialog_clear_places_cache_message": {
        "en": "Clear all looked-up place names, weather and wave data? The next download will look these up again (uses extra mobile data).",
        "nl": "Alle opgezochte plaatsnamen, weer- en golfgegevens wissen? Bij het eerstvolgende downloaden worden deze dan opnieuw opgezocht (kost extra mobiele data).",
        "fr": "Effacer tous les noms de lieux, données météo et de houle recherchés ? Le prochain téléchargement les recherchera à nouveau (consomme des données mobiles supplémentaires).",
        "de": "Alle abgerufenen Ortsnamen, Wetter- und Wellendaten löschen? Der nächste Download ruft diese dann erneut ab (kostet zusätzliche mobile Daten).",
    },
    "toast_cache_cleared": {
        "en": "Cache cleared",
        "nl": "Cache geleegd",
        "fr": "Cache vidé",
        "de": "Cache geleert",
    },
    "toast_settings_saved": {
        "en": "Settings saved",
        "nl": "Instellingen opgeslagen",
        "fr": "Paramètres enregistrés",
        "de": "Einstellungen gespeichert",
    },
    "log_fill_w2k2_credentials": {
        "en": "Fill in the W2K-2 username and password via Settings first.",
        "nl": "Vul eerst de W2K-2 gebruikersnaam en het wachtwoord in via Instellingen.",
        "fr": "Renseignez d'abord le nom d'utilisateur et le mot de passe W2K-2 dans les Paramètres.",
        "de": "Trage zuerst den W2K-2-Benutzernamen und das Passwort in den Einstellungen ein.",
    },
    "log_boat_busy": {
        "en": "Boat mode is busy with a round or a publish; try again in a moment.",
        "nl": "De boot-modus is bezig met een ronde of publicatie; probeer het zo opnieuw.",
        "fr": "Le mode bateau est occupé par une ronde ou une publication ; réessayez dans un instant.",
        "de": "Der Boot-Modus ist mit einer Runde oder Veröffentlichung beschäftigt; versuchen Sie es gleich noch einmal.",
    },
    "log_hotspot_precheck_skipped": {
        "en": "No private network detected (cheap pre-check) -- automatic download skipped.",
        "nl": "Geen privénetwerk gevonden (snelle controle) -- automatisch downloaden overgeslagen.",
        "fr": "Aucun réseau privé détecté (vérification rapide) -- téléchargement automatique ignoré.",
        "de": "Kein privates Netzwerk gefunden (schnelle Vorabprüfung) -- automatischer Download übersprungen.",
    },
    "status_importing": {
        "en": "Importing .ebl files...",
        "nl": ".ebl-bestanden importeren...",
        "fr": "Importation des fichiers .ebl...",
        "de": ".ebl-Dateien werden importiert...",
    },
    "log_import_no_files": {
        "en": "No .ebl files found there.",
        "nl": "Geen .ebl-bestanden gevonden.",
        "fr": "Aucun fichier .ebl trouvé.",
        "de": "Keine .ebl-Dateien gefunden.",
    },
    "log_import_copied": {
        "en": "Imported: {name}",
        "nl": "Geïmporteerd: {name}",
        "fr": "Importé : {name}",
        "de": "Importiert: {name}",
    },
    "log_import_done": {
        "en": "Imported {imported} .ebl file(s) ({skipped} already present, skipped).",
        "nl": "{imported} .ebl-bestand(en) geïmporteerd ({skipped} al aanwezig, overgeslagen).",
        "fr": "{imported} fichier(s) .ebl importé(s) ({skipped} déjà présent(s), ignoré(s)).",
        "de": "{imported} .ebl-Datei(en) importiert ({skipped} bereits vorhanden, übersprungen).",
    },
    "log_import_all_duplicates": {
        "en": "Nothing new -- all {count} .ebl file(s) found were already present.",
        "nl": "Niets nieuws -- alle {count} gevonden .ebl-bestand(en) waren al aanwezig.",
        "fr": "Rien de nouveau -- les {count} fichier(s) .ebl trouvé(s) étaient déjà présents.",
        "de": "Nichts Neues -- alle {count} gefundenen .ebl-Datei(en) waren bereits vorhanden.",
    },
    "log_import_renamed": {
        "en": "Same name, different content -- kept both: {detail}",
        "nl": "Zelfde naam, andere inhoud -- allebei bewaard: {detail}",
        "fr": "Même nom, contenu différent -- les deux ont été conservés : {detail}",
        "de": "Gleicher Name, anderer Inhalt -- beide behalten: {detail}",
    },
    "log_import_file_error": {
        "en": "Problem importing a file: {detail}",
        "nl": "Probleem bij importeren van een bestand: {detail}",
        "fr": "Problème lors de l'importation d'un fichier : {detail}",
        "de": "Problem beim Importieren einer Datei: {detail}",
    },
    "log_import_media_disconnected": {
        "en": "Connection to the SD card/USB drive was lost -- reconnect it and try again.",
        "nl": "Verbinding met de SD-kaart/USB-stick verloren -- opnieuw aansluiten en nogmaals proberen.",
        "fr": "Connexion à la carte SD/clé USB perdue -- reconnectez-la et réessayez.",
        "de": "Verbindung zur SD-Karte/zum USB-Speicher verloren -- erneut anschließen und noch einmal versuchen.",
    },
    "error_unexpected": {
        "en": "Unexpected error: {detail}",
        "nl": "Onverwachte fout: {detail}",
        "fr": "Erreur inattendue : {detail}",
        "de": "Unerwarteter Fehler: {detail}",
    },
    "log_fill_publish_settings": {
        "en": "Fill in the publish settings (REST or SFTP) via Settings first.",
        "nl": "Vul eerst de publiceer-instellingen (REST of SFTP) in via Instellingen.",
        "fr": "Renseignez d'abord les paramètres de publication (REST ou SFTP) dans les Paramètres.",
        "de": "Trage zuerst die Veröffentlichungseinstellungen (REST oder SFTP) in den Einstellungen ein.",
    },
    "status_uploading_wordpress": {
        "en": "Uploading to ayuus.com (to WordPress)...",
        "nl": "Uploaden naar ayuus.com (naar WordPress)...",
        "fr": "Envoi vers ayuus.com (vers WordPress)...",
        "de": "Wird auf ayuus.com hochgeladen (zu WordPress)...",
    },
    "log_upload_ok_wordpress": {
        "en": "Uploaded to WordPress: {url}",
        "nl": "Geüpload naar WordPress: {url}",
        "fr": "Envoyé vers WordPress : {url}",
        "de": "Zu WordPress hochgeladen: {url}",
    },
    "log_upload_failed_wordpress": {
        "en": "upload to WordPress failed: {error}",
        "nl": "upload naar WordPress mislukt: {error}",
        "fr": "l'envoi vers WordPress a échoué : {error}",
        "de": "Hochladen zu WordPress fehlgeschlagen: {error}",
    },
    "log_upload_not_configured": {
        "en": "Upload not configured",
        "nl": "Upload niet ingesteld",
        "fr": "Envoi non configuré",
        "de": "Upload nicht konfiguriert",
    },
    "log_no_logbook_to_view": {
        "en": "No logbook to view yet -- assemble one first.",
        "nl": "Nog geen logboek om te bekijken -- stel er eerst een samen.",
        "fr": "Aucun journal à consulter pour l'instant -- assemblez-en un d'abord.",
        "de": "Noch kein Bordbuch zum Ansehen -- zuerst eines zusammenstellen.",
    },
    "phase_downloading": {
        "en": "Downloading",
        "nl": "Downloaden",
        "fr": "Téléchargement",
        "de": "Herunterladen",
    },
    "phase_decoding": {
        "en": "Decoding",
        "nl": "Decoderen",
        "fr": "Décodage",
        "de": "Wird dekodiert",
    },
    "phase_building_trips": {
        "en": "Assembling trips",
        "nl": "Reizen samenstellen",
        "fr": "Assemblage des trajets",
        "de": "Fahrten werden zusammengestellt",
    },
    "phase_importing": {
        "en": "Importing",
        "nl": "Importeren",
        "fr": "Importation",
        "de": "Importieren",
    },
    "progress_label_format": {
        "en": "{phase}: {current}/{total}",
        "nl": "{phase}: {current}/{total}",
        "fr": "{phase} : {current}/{total}",
        "de": "{phase}: {current}/{total}",
    },
    "status_hotspot_off": {
        "en": "No private network detected (or the W2K-2 isn't on it) -- turn on your hotspot, or join the same network as the W2K-2, to download.",
        "nl": "Geen privénetwerk gevonden (of de W2K-2 zit er niet op) -- zet je hotspot aan, of verbind met hetzelfde netwerk als de W2K-2, om te downloaden.",
        "fr": "Aucun réseau privé détecté (ou le W2K-2 n'y est pas connecté) -- activez votre point d'accès, ou rejoignez le même réseau que le W2K-2, pour télécharger.",
        "de": "Kein privates Netzwerk gefunden (oder der W2K-2 ist nicht darauf) -- schalte deinen Hotspot ein oder verbinde dich mit demselben Netzwerk wie der W2K-2, um herunterzuladen.",
    },
    "status_listing_files": {
        "en": "Fetching file list (subnet {subnet}0/24)...",
        "nl": "Bestandenlijst ophalen (subnet {subnet}0/24)...",
        "fr": "Récupération de la liste des fichiers (sous-réseau {subnet}0/24)...",
        "de": "Dateiliste wird abgerufen (Subnetz {subnet}0/24)...",
    },
    "status_building_with_existing_data": {
        "en": "Assembling logbook with existing data...",
        "nl": "Logboek samenstellen met bestaande gegevens...",
        "fr": "Assemblage du journal avec les données existantes...",
        "de": "Bordbuch wird mit vorhandenen Daten zusammengestellt...",
    },
    "status_sync_cancelled": {
        "en": "Download cancelled.",
        "nl": "Downloaden geannuleerd.",
        "fr": "Téléchargement annulé.",
        "de": "Download abgebrochen.",
    },
    "status_build_cancelled": {
        "en": "Assembly cancelled.",
        "nl": "Samenstellen geannuleerd.",
        "fr": "Assemblage annulé.",
        "de": "Zusammenstellen abgebrochen.",
    },
    "status_cancel_still_stopping": {
        "en": "Still stopping; this can take a few more seconds.",
        "nl": "Nog bezig met stoppen; dit kan nog een paar seconden duren.",
        "fr": "Encore en train de s'arrêter ; cela peut prendre encore quelques secondes.",
        "de": "Wird noch beendet; das kann noch ein paar Sekunden dauern.",
    },
    "status_sync_stopped": {
        "en": "Download stopped. Next time it will resume where it left off.",
        "nl": "Downloaden gestopt. Volgende keer wordt verdergegaan waar het gebleven was.",
        "fr": "Téléchargement arrêté. Il reprendra où il s'est arrêté la prochaine fois.",
        "de": "Download gestoppt. Beim nächsten Mal wird dort fortgesetzt, wo er aufgehört hat.",
    },
    "status_build_stopped": {
        "en": "Assembly stopped. Next time it will resume where it left off.",
        "nl": "Samenstellen gestopt. Volgende keer wordt verdergegaan waar het gebleven was.",
        "fr": "Assemblage arrêté. Il reprendra où il s'est arrêté la prochaine fois.",
        "de": "Zusammenstellen gestoppt. Beim nächsten Mal wird dort fortgesetzt, wo es aufgehört hat.",
    },
    "status_ready_updated": {
        "en": "Ready (logbook updated).",
        "nl": "Klaar (logboek bijgewerkt).",
        "fr": "Terminé (journal mis à jour).",
        "de": "Fertig (Bordbuch aktualisiert).",
    },
    "status_ready_with_download": {
        "en": "Ready: {trips} trip(s), {files} file(s) downloaded.",
        "nl": "Klaar: {trips} reis(en), {files} bestand(en) gedownload.",
        "fr": "Terminé : {trips} trajet(s), {files} fichier(s) téléchargé(s).",
        "de": "Fertig: {trips} Fahrt(en), {files} Datei(en) heruntergeladen.",
    },
    "status_ready_no_download": {
        "en": "Ready: {trips} trip(s) (existing data, not re-downloaded).",
        "nl": "Klaar: {trips} reis(en) (bestaande gegevens, niet opnieuw gedownload).",
        "fr": "Terminé : {trips} trajet(s) (données existantes, non retéléchargées).",
        "de": "Fertig: {trips} Fahrt(en) (vorhandene Daten, nicht erneut heruntergeladen).",
    },
    "log_sync_done_at": {
        "en": "Done: {time}",
        "nl": "Voltooid: {time}",
        "fr": "Terminé : {time}",
        "de": "Fertig: {time}",
    },
    "log_no_ebl_files_to_build": {
        "en": "No .ebl files on this device yet -- nothing to assemble.",
        "nl": "Nog geen .ebl-bestanden op dit toestel -- niets om samen te stellen.",
        "fr": "Aucun fichier .ebl sur cet appareil pour l'instant -- rien à assembler.",
        "de": "Noch keine .ebl-Dateien auf diesem Gerät -- nichts zusammenzustellen.",
    },
    "error_generic_prefix": {
        "en": "Error: {error}",
        "nl": "Fout: {error}",
        "fr": "Erreur : {error}",
        "de": "Fehler: {error}",
    },
    "error_unknown": {
        "en": "unknown error",
        "nl": "onbekende fout",
        "fr": "erreur inconnue",
        "de": "unbekannter Fehler",
    },
    "error_unexpected_sync": {
        "en": "Unexpected error during download: {error}",
        "nl": "Onverwachte fout tijdens downloaden: {error}",
        "fr": "Erreur inattendue pendant le téléchargement : {error}",
        "de": "Unerwarteter Fehler während des Downloads: {error}",
    },
    "error_logbook_display_failed": {
        "en": "logbook could not be displayed: {error}",
        "nl": "logboek kon niet worden getoond: {error}",
        "fr": "impossible d'afficher le journal : {error}",
        "de": "Bordbuch konnte nicht angezeigt werden: {error}",
    },
    "log_publish_not_configured": {
        "en": "No publish destination configured -- publish button disabled.",
        "nl": "Geen publicatiebestemming ingesteld -- publiceerknop uitgeschakeld.",
        "fr": "Aucune destination de publication configurée -- bouton de publication désactivé.",
        "de": "Kein Veröffentlichungsziel eingerichtet -- Veröffentlichen-Schaltfläche deaktiviert.",
    },
    "hint_rest_upload_url": {
        "en": "your-site.example",
        "nl": "your-site.example",
        "fr": "your-site.example",
        "de": "your-site.example",
    },
}
