"""Writes the values both apps share (app_constants.py, app_settings.py) as the Android app's
``SharedConstants.kt``.

    python -m nmea2log.export_android_constants <path to SharedConstants.kt> [--check]

With ``--check`` nothing is written and the exit status says whether the file is up to date."""

from __future__ import annotations

import sys
from pathlib import Path
from typing import List

from . import app_constants, app_settings

_HEADER = """package com.ayuus.mysailinglogbook

// Generated by nmea2log.export_android_constants from nmea2log's app_constants.py and app_settings.py --
// do not edit by hand; change the Python and generate again.

"""


def _kotlin(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$")
        return f'"{escaped}"'
    if isinstance(value, tuple):
        return "listOf(" + ", ".join(_kotlin(item) for item in value) + ")"
    raise TypeError(f"no Kotlin form for {value!r}")


def render() -> str:
    lines: List[str] = [_HEADER, "object SharedConstants {\n"]
    for name in dir(app_constants):
        value = getattr(app_constants, name)
        if name.isupper() and not name.startswith("_"):
            keyword = "val" if isinstance(value, tuple) else "const val"
            lines.append(f"    {keyword} {name} = {_kotlin(value)}\n")
    lines.append("}\n\nobject SharedDefaults {\n")
    for name in ("DEFAULT_MIN_STOP_MINUTES", "DEFAULT_SFTP_PORT", "MINIMUM_MINUTES", "MINIMUM_PORT"):
        lines.append(f"    const val {name} = {_kotlin(getattr(app_settings, name))}\n")
    lines.append(f"    val BOOT_INTERVAL_CHOICES = {_kotlin(app_settings.BOOT_INTERVAL_CHOICES)}\n")
    for key, value in app_settings.DEFAULTS.items():
        lines.append(f"    const val {key.upper()} = {_kotlin(value)}\n")
    lines.append("}\n")
    return "".join(lines)


def main(argv: List[str]) -> int:
    check = "--check" in argv
    paths = [a for a in argv if not a.startswith("--")]
    if len(paths) != 1:
        print(__doc__)
        return 2
    path = Path(paths[0])
    wanted = render()
    current = path.read_text(encoding="utf-8").replace("\r\n", "\n") if path.exists() else None
    if current == wanted:
        print("up to date")
        return 0
    if check:
        print(f"{path} differs from the shared values")
        return 1
    path.write_text(wanted, encoding="utf-8", newline="")
    print(f"written {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
