"""Reads and writes ``remarks.csv``: free-text notes per trip, keyed by the trip's persistent
uid (see ``trip_ids.py``) rather than its date/time -- so a remark survives a future
trip-recognition fix that shifts a trip's exact departure/arrival time.

Not generated by nmea2log itself; edited via ``nmea2log-edit`` (see ``remarks_server.py``) or by
hand in a spreadsheet. Read back in by ``cli.py`` on every run and merged into the CSV/HTML
output.
"""

from __future__ import annotations

import csv
from pathlib import Path
from typing import Dict

DEFAULT_REMARKS_PATH = Path("remarks.csv")

_FIELDNAMES = ["uid", "date", "departure_port", "arrival_port", "remark"]


def load_remarks(path: Path = DEFAULT_REMARKS_PATH) -> Dict[str, str]:
    """Returns {uid: remark}. Missing file or missing/blank remark for a uid simply means no
    remark -- not an error."""
    if not path.exists():
        return {}
    with path.open("r", newline="", encoding="utf-8-sig") as handle:
        reader = csv.DictReader(handle, delimiter=";")
        return {row["uid"]: row["remark"] for row in reader if row.get("uid") and row.get("remark")}


def save_remarks(remarks: Dict[str, str], trip_labels: Dict[str, str], path: Path = DEFAULT_REMARKS_PATH) -> None:
    """``trip_labels``: {uid: "date|departure_port|arrival_port"} for the extra, human-readable
    (but not read back in) columns -- so the file is easy to eyeball or edit directly in a
    spreadsheet without needing to decode a uid first."""
    with path.open("w", newline="", encoding="utf-8-sig") as handle:
        writer = csv.DictWriter(handle, fieldnames=_FIELDNAMES, delimiter=";")
        writer.writeheader()
        for uid in sorted(remarks, key=lambda u: trip_labels.get(u, u)):
            date, _, rest = trip_labels.get(uid, "||").partition("|")
            departure_port, _, arrival_port = rest.partition("|")
            writer.writerow(
                {
                    "uid": uid,
                    "date": date,
                    "departure_port": departure_port,
                    "arrival_port": arrival_port,
                    "remark": remarks[uid],
                }
            )
